apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: it-messaging-service
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cloudsql-instances: "YOUR_PROJECT_ID:YOUR_REGION:YOUR_PROD_INSTANCE_ID"
        autoscaling.knative.dev/maxScale: "100"
        autoscaling.knative.dev/minScale: "2"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/it-messaging-service:latest # This will be replaced by the build script
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "warn"
        - name: DB_HOST
          value: "/cloudsql/YOUR_PROJECT_ID:YOUR_REGION:YOUR_PROD_INSTANCE_ID"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "your_prod_user" # Replace with your production DB user
        - name: DB_NAME
          value: "messaging_service" # Or your production DB name
        - name: DB_SSL_MODE
          value: "disable"
        - name: REDIS_ENABLED
          value: "false" # Or true if you use it in prod
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: latest
              name: it-chatbot-jwt-password
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: latest
              name: it-chatbot-db-password

        resources:
          limits:
            cpu: "2"
            memory: "1Gi"
          requests:
            cpu: "1"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/ready
            port: 8080
          periodSeconds: 5